app:
  # Persistence
  persistence:
    jpa:
      generate-ddl: true
      show-sql: true
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      username: 'root'
      password: '1z3rt1s'
      rootUsername: 'root'
      rootPassword: '1z3rt1s'
      url: jdbc:mariadb://localhost:3307/uris?ssl=false&createDatabaseIfNotExist=true
      #jdbc:mariadb://127.0.0.1:3307/uris?ssl=false&createDatabaseIfNotExist=true
  # Swagger
  swagger:
    enabled: true
    secured: false
#    authServerUrl: ../oauth
#    authServerClientId: acme
#    authServerClientSecret: acmesecret

## Actuator
management:
  health:
    redis:
      enabled: false
  server:
    port: 9326

server:
    port: 9326
