---
app:
  persistence:
    datasource:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: admin123
      url: jdbc:postgresql://127.0.0.1:5432/app?ssl=false
    jpa:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      generate-ddl: false
      show-sql: true
      properties:
        hibernate.temp.use_jdbc_metadata_defaults: false
    uri:
      canonicalURISchema: http://$domain$/$sub-domain$/$type$/$concept$/$reference$
      canonicalURILanguageSchema: http://$domain$/$sub-domain$/$language$/$type$/$concept$/$reference$

  # CORS
  cors:
    enabled: true
    allowedOrigin: '*'
    allowedMethods: GET,POST,PUT,DELETE
    allowedHeaders:
      - Authorization
      - X-Requested-With
      - Content-Type
    maxAge: 3600

  # Cache configuration
  cache:
    embedded:
      enabled: true

  # Swagger
  swagger:
    enabled: false

## Actuator
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /management
  server:
    port: 9321
  health:
    mail:
      enabled: false
    ldap:
      enabled: false
    redis:
      enabled: false
