app:
  # Persistence
  persistence:
    jpa:
      generate-ddl: true
      show-sql: true
    datasource:
       username: root
       password: root
       rootUsername: root
       rootPassword: root
       url: jdbc:mariadb://127.0.0.1:3307/uris?ssl=false&createDatabaseIfNotExist=true
  # Swagger
  swagger:
    enabled: true
    secured: false
#    authServerUrl: ../oauth
#    authServerClientId: acme
#    authServerClientSecret: acmesecret

## Actuator
management:
  health:
    redis:
      enabled: false
  server:
    port: 9326

server:
    port: 9326
