version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: unless-stopped
    ports:
      #      - "3306:3306"
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      # MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: root
      # CONFIG - Change the default values below (should match values passed to wikibase)
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'sqlpass'
    networks:
      default:
        aliases:
          - mysql.svc

volumes:
  mysql-data:
